# Generated by Django 5.1.2 on 2024-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='support_level',
            field=models.CharField(choices=[('low_risk', 'Low Risk'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], default='low_risk', max_length=20),
        ),
    ]
