# Generated by Django 5.1.2 on 2024-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chat_support_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(max_length=1000),
        ),
    ]
